/**
 * Generic model dedup for a single brand — Strapi side.
 *
 * Generalizes dedupe-renault-models.js (which used a hand-verified,
 * hardcoded canonical slug per duplicate-name group) into a brand-agnostic
 * script driven by an automated heuristic, so it scales beyond one brand
 * without manually cross-referencing every group:
 *
 *   canonical = the duplicate whose slug is already in the frontend's
 *   referenced_vehicles.json whitelist > else the one with more real
 *   product rows attached (battery_products flat columns + the three
 *   *_model_lnk join tables) > else the lowest id.
 *
 * Duplicates are detected by EXACT name match only (never fuzzy) — the
 * same conservative rule used throughout this cleanup, deliberately
 * avoiding the backend's own pre-existing scripts/deduplicate-models.js
 * toolchain, whose fuzzy 0.90-similarity detectDuplicates() has no
 * protection against generation markers and groups things like
 * "ACCORD III" with "ACCORD VIII" as if they were the same model.
 *
 * Each duplicate "model" is a documentId with a draft row + a published
 * row (Strapi v5 draft/publish). Migration preserves that pairing:
 * relations get moved draft-id -> canonical-draft-id and
 * published-id -> canonical-published-id, never mixed.
 *
 * Deactivates (is_active = 0) rather than deletes the losing rows.
 *
 * Usage: node scripts/dedupe-models.js <brandSlug> [dbPath]
 * (dbPath defaults to .tmp/data.db relative to cwd)
 */

const fs = require('fs');
const path = require('path');
const Database = require('better-sqlite3');

const DEFAULT_DB_PATH = path.join(process.cwd(), '.tmp', 'data.db');
// Sibling repo on the same filesystem — the whitelist is generated by the
// frontend's own tooling, not duplicated here.
const REFERENCED_VEHICLES_PATH = path.join(
  __dirname, '..', '..', 'react-app-tablet', 'public', 'assets', 'data', 'referenced_vehicles.json'
);

const LNK_TABLES = [
  { table: 'lights_products_model_lnk' },
  { table: 'wipers_products_model_lnk' },
  { table: 'filter_compatibilities_model_lnk' },
];

function loadReferencedSlugs(brandSlug) {
  if (!fs.existsSync(REFERENCED_VEHICLES_PATH)) return new Set();
  const data = JSON.parse(fs.readFileSync(REFERENCED_VEHICLES_PATH, 'utf-8'));
  const brand = data.brands?.[brandSlug];
  return new Set(brand ? Object.keys(brand.models || {}) : []);
}

function countProductRows(db, brandSlug, ids) {
  let total = 0;
  for (const { table } of LNK_TABLES) {
    for (const id of ids) {
      const row = db.prepare(`SELECT COUNT(*) as cnt FROM ${table} WHERE model_id = ?`).get(id);
      total += row.cnt;
    }
  }
  return total;
}

function countBatteryRows(db, brandSlug, slugs) {
  let total = 0;
  for (const slug of slugs) {
    const row = db.prepare(
      `SELECT COUNT(*) as cnt FROM battery_products WHERE brand_slug = ? AND model_slug = ?`
    ).get(brandSlug, slug);
    total += row.cnt;
  }
  return total;
}

function main() {
  const brandSlug = process.argv[2];
  const dbPath = process.argv[3] || DEFAULT_DB_PATH;

  if (!brandSlug) {
    console.error('Usage: node scripts/dedupe-models.js <brandSlug> [dbPath]');
    process.exit(1);
  }

  console.log(`=== Model dedup (Strapi) for "${brandSlug}" — ${dbPath} ===`);

  const db = new Database(dbPath);
  const referencedSlugs = loadReferencedSlugs(brandSlug);

  const rows = db.prepare(`
    SELECT m.id, m.document_id as documentId, m.name, m.slug, m.published_at IS NOT NULL as isPublished
    FROM models m
    JOIN models_brand_lnk lnk ON lnk.model_id = m.id
    JOIN brands b ON b.id = lnk.brand_id
    WHERE b.slug = ? AND m.is_active = 1
    ORDER BY m.name, m.id
  `).all(brandSlug);

  // Group rows into documents (draft + published pair sharing one documentId).
  const byDoc = new Map();
  for (const r of rows) {
    if (!byDoc.has(r.documentId)) byDoc.set(r.documentId, { documentId: r.documentId, name: r.name, rows: [] });
    byDoc.get(r.documentId).rows.push(r);
  }
  const docs = Array.from(byDoc.values());

  // Group documents by exact name.
  const byName = new Map();
  for (const doc of docs) {
    if (!byName.has(doc.name)) byName.set(doc.name, []);
    byName.get(doc.name).push(doc);
  }

  const migrateLnk = {};
  for (const { table } of LNK_TABLES) {
    migrateLnk[table] = db.prepare(`UPDATE ${table} SET model_id = ? WHERE model_id = ?`);
  }
  const migrateBattery = db.prepare(
    `UPDATE battery_products SET model_slug = ? WHERE brand_slug = ? AND model_slug = ?`
  );
  const deactivateModel = db.prepare(`UPDATE models SET is_active = 0 WHERE id = ?`);

  let migratedLnkRows = 0;
  let migratedBatteryRows = 0;
  let deactivatedModels = 0;
  let groupsProcessed = 0;

  for (const [name, group] of byName) {
    if (group.length <= 1) continue;
    groupsProcessed++;

    const scored = group.map(doc => {
      const ids = doc.rows.map(r => r.id);
      const slugs = [...new Set(doc.rows.map(r => r.slug))];
      const isReferenced = slugs.some(s => referencedSlugs.has(s));
      const dataCount = countProductRows(db, brandSlug, ids) + countBatteryRows(db, brandSlug, slugs);
      return { ...doc, isReferenced, dataCount, minId: Math.min(...ids) };
    });
    scored.sort((a, b) => {
      if (a.isReferenced !== b.isReferenced) return a.isReferenced ? -1 : 1;
      if (a.dataCount !== b.dataCount) return b.dataCount - a.dataCount;
      return a.minId - b.minId;
    });

    const canonical = scored[0];
    const losers = scored.slice(1);
    const canonicalDraft = canonical.rows.find(r => !r.isPublished);
    const canonicalPublished = canonical.rows.find(r => r.isPublished);
    const canonicalSlug = (canonicalPublished ?? canonicalDraft).slug;

    console.log(`\n"${name}" — canonical documentId ${canonical.documentId} (slug ${canonicalSlug}, referenced=${canonical.isReferenced}, data=${canonical.dataCount})`);

    for (const loser of losers) {
      const losingDraft = loser.rows.find(r => !r.isPublished);
      const losingPublished = loser.rows.find(r => r.isPublished);
      console.log(`  losing documentId ${loser.documentId} (slug ${loser.rows[0].slug}, data=${loser.dataCount})`);

      const pairs = [
        [losingDraft, canonicalDraft],
        [losingPublished, canonicalPublished],
      ];

      for (const { table } of LNK_TABLES) {
        for (const [losing, canonicalRow] of pairs) {
          if (!losing || !canonicalRow) continue;
          try {
            const result = migrateLnk[table].run(canonicalRow.id, losing.id);
            if (result.changes > 0) {
              console.log(`    migrated ${result.changes} row(s) in ${table}: model_id ${losing.id} -> ${canonicalRow.id}`);
              migratedLnkRows += result.changes;
            }
          } catch (err) {
            console.log(`    skipped ${table} migration for ${losing.id} -> ${canonicalRow.id}: ${err.message}`);
          }
        }
      }

      for (const losingSlug of [...new Set(loser.rows.map(r => r.slug))]) {
        const batteryResult = migrateBattery.run(canonicalSlug, brandSlug, losingSlug);
        if (batteryResult.changes > 0) {
          console.log(`    migrated ${batteryResult.changes} row(s) in battery_products: ${losingSlug} -> ${canonicalSlug}`);
          migratedBatteryRows += batteryResult.changes;
        }
      }

      for (const r of loser.rows) {
        deactivateModel.run(r.id);
        console.log(`    deactivated model id ${r.id} (${r.slug}, published=${!!r.isPublished})`);
        deactivatedModels++;
      }
    }
  }

  db.close();

  console.log('\n=== Summary ===');
  console.log(`Duplicate-name groups processed: ${groupsProcessed}`);
  console.log(`_model_lnk rows migrated: ${migratedLnkRows}`);
  console.log(`battery_products rows migrated: ${migratedBatteryRows}`);
  console.log(`Models deactivated: ${deactivatedModels}`);
}

main();
